version: "3"
services:
  test01:
    build: .
    image: registry.cn-beijing.aliyuncs.com/wangdali/jenkins-test01
  test02:
    build: .
    image: registry.cn-beijing.aliyuncs.com/wangdali/jenkins-test02
